# Generated by Django 4.0.4 on 2022-05-26 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supertype',
            name='is_hero',
        ),
        migrations.AddField(
            model_name='supertype',
            name='type',
            field=models.CharField(default='Heroes', max_length=255),
            preserve_default=False,
        ),
    ]
